export const colors = {
    primary: '#f472b6',
    primaryDeep: '#db2777',
    primaryMild: '#f9a8d4',
    primarySubtle: '#f472b61a',
    secondary: '#8b5cf6',
    secondaryDeep: '#7c3aed',
    secondaryMild: '#a78bfa',
    secondarySubtle: '#8b5cf61a',
    accent: '#06b6d4',
    neutral: '#ffffff',
    background: '#fdf2f8',
    textPrimary: '#1a1d1f',
    textSecondary: '#6f767e',
    textAccent: '#f472b6',
    borderColor: '#e6e8ec',
    cardBg: '#ffffff',
    buttonBg: '#f472b6',
    buttonText: '#ffffff',
    inputBg: '#ffffff',
    inputText: '#1a1d1f',
    heroBg: '#f472b6',
    heroText: '#ffffff'
}
