export const colors = {
    primary: '#0CAF60',
    primaryDeep: '#088d50',
    primaryMild: '#34c779',
    primarySubtle: '#0CAF601a',
    secondary: '#3b82f6',
    secondaryDeep: '#2563eb',
    secondaryMild: '#60a5fa',
    secondarySubtle: '#3b82f61a',
    accent: '#f59e0b',
    neutral: '#ffffff',
    background: '#f0fdf4',
    textPrimary: '#1a1d1f',
    textSecondary: '#6f767e',
    textAccent: '#0CAF60',
    borderColor: '#e6e8ec',
    cardBg: '#ffffff',
    buttonBg: '#0CAF60',
    buttonText: '#ffffff',
    inputBg: '#ffffff',
    inputText: '#1a1d1f',
    heroBg: '#0CAF60',
    heroText: '#ffffff'
}
