export const colors = {
    primary: '#2a85ff',
    primaryDeep: '#0069f6',
    primaryMild: '#4996ff',
    primarySubtle: '#2a85ff1a',
    secondary: '#5d5fef',
    secondaryDeep: '#4a4cbe',
    secondaryMild: '#7e80f1',
    secondarySubtle: '#5d5fef1a',
    accent: '#00c8ff',
    neutral: '#ffffff',
    background: '#f5f5f7',
    textPrimary: '#1a1d1f',
    textSecondary: '#6f767e',
    textAccent: '#2a85ff',
    borderColor: '#e6e8ec',
    cardBg: '#ffffff',
    buttonBg: '#2a85ff',
    buttonText: '#ffffff',
    inputBg: '#ffffff',
    inputText: '#1a1d1f',
    heroBg: '#2a85ff',
    heroText: '#ffffff'
}
